In [32]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error,mean_absolute_percentage_error

In [3]:
df = pd.read_csv("insurance.csv")

In [32]:
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [5]:
cols_to_encode = ["sex", "smoker", "region"]
if all(col in df.columns for col in cols_to_encode):
    df = pd.get_dummies(df, columns=cols_to_encode, drop_first=True)

In [6]:
df.head(3)

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.90,0,16884.9240,False,True,False,False,True
1,18,33.77,1,1725.5523,True,False,False,True,False
2,28,33.00,3,4449.4620,True,False,False,True,False

In [7]:
y = df["charges"]
X = df.drop("charges", axis=1)

In [8]:
lm = LinearRegression()
model = lm.fit(X,y)

In [10]:
model.score(X,y)

0.7509130345985207

In [11]:
df_error = pd.DataFrame()

In [13]:
df_error['y']=y

In [14]:
df_error

                y
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [17]:
y_estimate = model.predict(X)

In [19]:
df_error['estimate']=y_estimate

In [20]:
df_error

                y      estimate
0     16884.92400  25293.713028
1      1725.55230   3448.602834
2      4449.46200   6706.988491
3     21984.47061   3754.830163
4      3866.85520   5592.493386
...           ...           ...
1333  10600.54830  12351.323686
1334   2205.98080   3511.930809
1335   1629.83350   4149.132486
1336   2007.94500   1246.584939
1337  29141.36030  37085.623268

[1338 rows x 2 columns]

In [22]:
df_error['error']=df_error['y']-df_error['estimate']

In [23]:
df_error

                y      estimate         error
0     16884.92400  25293.713028  -8408.789028
1      1725.55230   3448.602834  -1723.050534
2      4449.46200   6706.988491  -2257.526491
3     21984.47061   3754.830163  18229.640447
4      3866.85520   5592.493386  -1725.638186
...           ...           ...           ...
1333  10600.54830  12351.323686  -1750.775386
1334   2205.98080   3511.930809  -1305.950009
1335   1629.83350   4149.132486  -2519.298986
1336   2007.94500   1246.584939    761.360061
1337  29141.36030  37085.623268  -7944.262968

[1338 rows x 3 columns]

In [25]:
df_error['MSE'] = df_error['error']**2

In [27]:
df_error

                y      estimate         error           MSE
0     16884.92400  25293.713028  -8408.789028  7.070773e+07
1      1725.55230   3448.602834  -1723.050534  2.968903e+06
2      4449.46200   6706.988491  -2257.526491  5.096426e+06
3     21984.47061   3754.830163  18229.640447  3.323198e+08
4      3866.85520   5592.493386  -1725.638186  2.977827e+06
...           ...           ...           ...           ...
1333  10600.54830  12351.323686  -1750.775386  3.065214e+06
1334   2205.98080   3511.930809  -1305.950009  1.705505e+06
1335   1629.83350   4149.132486  -2519.298986  6.346867e+06
1336   2007.94500   1246.584939    761.360061  5.796691e+05
1337  29141.36030  37085.623268  -7944.262968  6.311131e+07

[1338 rows x 4 columns]

In [28]:
df_error["MAE"] = abs(df_error['error'])

In [29]:
df_error['Percent_error'] = np.abs((y-y_estimate)/y)

In [30]:
df_error

,y,estimate,error,MSE,MAE,Percent_error
0,16884.92400,25293.713028,-8408.789028,7.070773e+07,8408.789028,0.498006
1,1725.55230,3448.602834,-1723.050534,2.968903e+06,1723.050534,0.998550
2,4449.46200,6706.988491,-2257.526491,5.096426e+06,2257.526491,0.507371
3,21984.47061,3754.830163,18229.640447,3.323198e+08,18229.640447,0.829205
4,3866.85520,5592.493386,-1725.638186,2.977827e+06,1725.638186,0.446264
...,...,...,...,...,...,...
1333,10600.54830,12351.323686,-1750.775386,3.065214e+06,1750.775386,0.165159
1334,2205.98080,3511.930809,-1305.950009,1.705505e+06,1305.950009,0.592004
1335,1629.83350,4149.132486,-2519.298986,6.346867e+06,2519.298986,1.545740
1336,2007.94500,1246.584939,761.360061,5.796691e+05,761.360061,0.379174
1337,29141.36030,37085.623268,-7944.262968,6.311131e+07,7944.262968,0.272611

In [34]:
df_error.mean()

y                1.327042e+04
estimate         1.327042e+04
error            2.289371e-12
MSE              3.650189e+07
MAE              4.170887e+03
Percent_error    4.203527e-01
dtype: float64

In [36]:
mean_squared_error(y,y_estimate)

36501893.00741544

In [37]:
mean_absolute_error(y,y_estimate)

4170.886894163586

In [38]:
mean_absolute_percentage_error(y,y_estimate)

0.4203526847372702